[package]
name = "romano"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
cucumber = "0.20.2"
futures = "0.3"


[[test]]
name = "tuples"
harness = false
